@startuml
'https://plantuml.com/sequence-diagram

autonumber

Game -> FileIO: String[] data = readBoardData()

Game -> Board : new(data)
Board -> Board : createFields()
Board -> Field : new()

@enduml