@startuml
autonumber

participant Game as game
participant Dice as dice
participant Player as player
participant Board as board
participant Field as field
game -> game : runGameLoop()
game -> game : throwAndMove()
game -> dice : int result = rollDiceSum()
game -> player: int newPosition = updatePosition( result )
game -> board : Field f = getField( newPosition )
game -> field : String msg = f.onLand()

@enduml